### ISSUE TITLE
Taskpool Cockpit application not starting

### ISSUE THREAD

**Issue by jangalinski** [holunda-io/polyflow-examples#84]
### Steps to reproduce

* start docker compose (.docker/setup.sh, docker compose up)
* start app in IDEA

### Expected behaviour

application runs

### Actual behaviour

Startup fails:

```
2022-05-04 08:57:31.554 ERROR 70521 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Invalid mapping pattern detected: /taskpool-cockpit/**/*.png
                 ^
No more pattern data allowed after {*...} or ** pattern element

Action:

Fix this pattern in your application or switch to the legacy parser implementation with 'spring.mvc.pathmatch.matching-strategy=ant_path_matcher'.

```

**Comment by zambrovski** [comment]
Taskpool Cockpit is an old abandoned component that was initially designed to look for Tasks and Events available in Taskppol / Datapool. We should delete it eventually...

**Comment by zambrovski** [comment]
I can make it run - but you don't want to use..

**Comment by zambrovski** [comment]
Fun fact - I already deleted the entire frontend - so the remaining part is only accessible via REST for debugging...
