### ISSUE TITLE
distributed scenario: platform application - provided links do not work

### ISSUE THREAD

**Issue by jangalinski** [holunda-io/polyflow-examples#85]
### Steps to reproduce

* start docker env (setup.sh && docker compose up)
* start ExamplePlatformApplicationDistributedWithAxonServer application (in IDEA)
* inspect the links in the banner:

```
 Task list URL:                   http://localhost:8081/polyflow/tasks
 Business data entries list URL:  http://localhost:8081/polyflow/archive
```

### Expected behaviour

* provided links can be clicked and lead to useful information

### Actual behaviour

* provided links lead to 404/whitelabel error page

**Comment by jangalinski** [comment]
related to #84 ?

**Comment by zambrovski** [comment]
Works for me... 

https://www.holunda.io/camunda-bpm-taskpool/latest/examples/scenarios/distributed-axon-server.html#preparations

Before you begin, please build the entire project with `mvn clean install` from the command line in the project root directory.

**Comment by jangalinski** [comment]
Thanks for checking, will try again
